"""Deeper FA-HPPO failure analysis from frozen V3 raw rows only.

Does not replay TEST policies or reconstruct unrecorded trajectories.
Publication figure: generated by scripts/paper/build_results_paper.py
(figA05_failure_analysis.{pdf,png}).
"""

from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts" / "v3"))
from common import SEEDS, V3  # noqa: E402

RAW = V3 / "raw" / "synthcharge_test.jsonl"
OUT = ROOT / "results" / "v3" / "paper" / "failure_analysis"
FIG_NOTE = "results/v3/paper/figures/fig17_failure_by_regime.png"


def main() -> None:
    rows = [json.loads(line) for line in RAW.read_text(encoding="utf-8").splitlines() if line.strip()]
    hybrid = [r for r in rows if r["method"] == "HybridPPO"]
    by_route = defaultdict(list)
    for r in hybrid:
        by_route[r["route_id"]].append(r)

    fail_counts = []
    route_records = []
    for rid, rr in sorted(by_route.items()):
        n_fail = sum(1 for r in rr if not r["feasible"])
        fail_counts.append(n_fail)
        if n_fail == 0:
            continue
        fails = [r for r in rr if not r["feasible"]]
        oks = [r for r in rr if r["feasible"]]
        sample = fails[0]
        route_records.append(
            {
                "route_id": rid,
                "layout": sample.get("layout"),
                "length_bin": sample.get("length_bin"),
                "charge_class": sample.get("charge_class"),
                "n_seeds_fail": n_fail,
                "fail_seeds": sorted(int(r["seed"]) for r in fails),
                "ok_seeds": sorted(int(r["seed"]) for r in oks),
                "reason": sample.get("reason"),
            }
        )

    conc = Counter(fail_counts)
    reason_counts = Counter(r.get("reason") for r in hybrid if not r["feasible"])
    per_seed = Counter(int(r["seed"]) for r in hybrid if not r["feasible"])
    all5 = [rec for rec in route_records if rec["n_seeds_fail"] == 5]
    any_fail = [rec for rec in route_records if rec["n_seeds_fail"] >= 1]
    exactly1 = [rec for rec in route_records if rec["n_seeds_fail"] == 1]

    findings = {
        "n_routes": len(by_route),
        "n_route_seed_failures": sum(fail_counts),
        "routes_with_any_failure": len(any_fail),
        "routes_failing_all_5_seeds": len(all5),
        "routes_failing_exactly_1_seed": len(exactly1),
        "routes_all_seeds_ok": conc.get(0, 0),
        "failure_consistency_histogram": {str(k): conc.get(k, 0) for k in range(0, 6)},
        "failures_per_seed": {str(s): per_seed.get(s, 0) for s in SEEDS},
        "reason_counts": dict(reason_counts),
        "answers": {
            "few_hard_routes": (
                f"{len(any_fail)}/{len(by_route)} routes fail for >=1 seed; "
                f"{conc.get(0, 0)}/{len(by_route)} succeed for all 5 seeds; "
                f"{len(all5)} fail for all 5."
            ),
            "same_routes_all_seeds": f"{len(all5)} routes fail under all five seeds: "
            + ", ".join(r["route_id"] for r in all5),
            "layout_length_concentration": "See figA05 panel (b) / tableA03; computed from frozen raw only.",
            "seed_46_vs_45": f"seed45={per_seed.get(45, 0)} failures; seed46={per_seed.get(46, 0)} failures.",
            "all_ok_vs_multi_fail": (
                f"{conc.get(0, 0)} routes all-seed OK vs {len(any_fail)} with any failure; "
                "distinguishing features beyond layout/length/charge_class require trajectories not stored in V3 raw."
            ),
        },
        "unavailable": [
            "step-level pre-failure TEST trajectories (not recorded in V3 raw)",
            "causal action sequences immediately before NO_FEASIBLE_ACTION without TEST replay",
        ],
        "routes": route_records,
    }

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "FINDINGS.json").write_text(json.dumps(findings, indent=2) + "\n", encoding="utf-8")

    lines = [
        "# FA-HPPO failure analysis (frozen V3 raw)",
        "",
        "**No TEST replay. No unrecorded trajectory reconstruction.**",
        "",
        f"- Routes: {findings['n_routes']}",
        f"- Route×seed failures: {findings['n_route_seed_failures']}",
        f"- Routes with any failure: {findings['routes_with_any_failure']}",
        f"- Routes failing all 5 seeds: {findings['routes_failing_all_5_seeds']}",
        f"- Routes failing exactly 1 seed: {findings['routes_failing_exactly_1_seed']}",
        f"- Failures per seed: {findings['failures_per_seed']}",
        f"- Seed 46 vs 45: {findings['answers']['seed_46_vs_45']}",
        f"- Reasons: {findings['reason_counts']}",
        "",
        "## Answers",
        "",
    ]
    for k, v in findings["answers"].items():
        lines.append(f"- **{k}:** {v}")
    lines += [
        "",
        "## Unavailable without TEST replay",
        "",
    ]
    lines += [f"- {u}" for u in findings["unavailable"]]
    lines += [
        "",
        "Publication table: `results/v3/paper/tables/tableA03_failure_routes.*`",
        f"Figure (official builder): `{FIG_NOTE}`",
        "",
        "Regenerate publication figures with `python scripts/paper/build_results_paper.py`.",
    ]
    (OUT / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps({"wrote": str(OUT), "n_fail_routes": len(route_records), "all5": len(all5)}, indent=2))


if __name__ == "__main__":
    main()
